### ISSUE TITLE
Documentación: listar tarjetas de pruebas

### ISSUE THREAD

**Issue by olivermontes** [DevopensourceTeam/Devopensource_Redsys#10]
Añadir las tarjetas de prueba a la documentación de todos los diferentes bancos

**Comment by ojurado-azk** [comment]
Para La Caixa en Entorno Test:

Tarjeta prueba Autorizada:
Número de tarjeta  4548812049400004
Caducidad   12/20
Código CVV2    123
Código CIP 123456

Tarjeta prueba Denegada:
Número de tarjeta  1111111111111117
Caducidad   12/20
