### ISSUE TITLE
Código de respuesta y autorización en pedido

### ISSUE THREAD

**Issue by ojurado-azk** [DevopensourceTeam/Devopensource_Redsys#12]
Al volver de Redsys, si el pago está aceptado, sería conveniente que en el pedido ponga el código de autorización.
Ejemplo:
Pago TPV aceptado (respuesta: 0000, autorizacion: 123456) 

Y en caso de denegación, que además de la descripción pusiera el código de error.
Ejemplo:
Error: Tarjeta ajena al servicio (respuesta: 180)

**Comment by mbernabeu** [comment]
Me parece una funcionalidad necesaria me pongo con ello muchas gracias

**Comment by mbernabeu** [comment]
Ya esta disponible en la version 0.1.2
