### ISSUE TITLE
Fallo CHECK_RECURRING_PROFILES en Release 0.1.2

### ISSUE THREAD

**Issue by ojurado-azk** [DevopensourceTeam/Devopensource_Redsys#17]
Después de actualizar a Release 0.1.2, al entrar en la tienda en /checkout/onepage/ se queda la página en blanco. 
Mirando los log de acceso veo un error 500:
`"GET /checkout/onepage/ HTTP/1.1" 500 -`

Mirando el log de errores de Apache, aparece un error:
`PHP Fatal error:  Undefined class constant 'CHECK_RECURRING_PROFILES' in XXXXX\\app\\code\\local\\Devopensource\\Redsys\\Model\\Redsys.php on line 45, referer: http://xxxxx/checkout/cart/`

La versión de Magento es la 1.7.0.1

**Comment by mbernabeu** [comment]
Puede que sea por la version de Magento prueba a añadir la siguiente linea debajo de la definición de las variables 

 const CHECK_RECURRING_PROFILES    = 64;

en el fichero app\code\local\Devopensource\Redsys\Model\Redsys.php

@ojurado-azk mira a ver si con esto se soluciona, si no háznoslo saber para solucionarlo

**Comment by ojurado-azk** [comment]
Da un error de Magento del tipo:

There has been an error processing your request
Exception printing is disabled by default for security reasons.
Error log record number: 1807103935

Estoy buscando por los logs a ver si veo algo...

**Comment by olivermontes** [comment]
@ojurado-azk vamos a probarlo en un Magento de la misma version, Gracias por reportar el error.

**Comment by ojurado-azk** [comment]
He comentado toda la función "isAvailable" en app\code\local\Devopensource\Redsys\Model\Redsys.php y al menos no da el error y funciona...

**Comment by mbernabeu** [comment]
Si se comenta eso perderas la funcionalidad para debug para que solo le aparezca a los desarrolladores pero el resto funcionara sin problema

**Comment by mbernabeu** [comment]
Acabo de subir un fix que solventa este problema
