### ISSUE TITLE
/redsys/index/callback - 404 Not Found

### ISSUE THREAD

**Issue by ddisseny** [DevopensourceTeam/Devopensource_Redsys#18]
Merchant URL,
/redsys/index/callback   Error 404

Error en la notificación, ya que no enruta la url de notificación.

Magento 1.7

**Comment by mbernabeu** [comment]
Hola

As limpiado cache de Magento?

**Comment by ddisseny** [comment]
Si,

Pede ser por Multitienda (Idiomas)? **/es/_**/redsys/index/callback

**Comment by mbernabeu** [comment]
prueba a poner en la url
www.tudominio.com/es/redsys/index/callback
www.tudominio.com/redsys/index/callback

mira si alguna responde con una redirección en lugar de con una 404

**Comment by ddisseny** [comment]
Si el error es ese!

Habría que cambiar la configuración para que se pueda seleccionr el STORE_URL

**Comment by ddisseny** [comment]
Ya he hecho una prueba real, y con el "store URL" funciona

**Comment by luisestudioalfa** [comment]
Hola,

Creo que tengo el mismo problema.... ¿Como puedo solventarlo?

Muchas gracias de antemano
