### ISSUE TITLE
Importe 0 Sin Asignar

### ISSUE THREAD

**Issue by DarkYamik** [DevopensourceTeam/Devopensource_Redsys#19]
Como podreis ver en la imagen, el importe de la compra me aparece como 0 (en cualquier caso, si hago una compra por 200€ me sale lo mismo), hace falta decir que la clave SHA-256 no es correcta, como se puede ver con el error SIS0042, pero eso esta controlado y estoy en espera de la nueva clave. Esto se podria deber al modulo o es otra cosa?

PD: Es la primera vez que escribo en GitHub asi que disculpen si me he equivocado de seccion :P

![image](https://cloud.githubusercontent.com/assets/15999197/11367338/43c6d872-92b3-11e5-88ee-beabf455baaf.png)

**Comment by mbernabeu** [comment]
Es por la firma en cuanto pongas la firma correcta se enviara el importe correctamente.

Si estas en el entorno de test la clave sha256 creo que es generica prueba a ver si te funciona con esta
sq7HjrUOBfKmC576ILgskD5srU870gJ7

**Comment by ojurado-azk** [comment]
Es la misma clave que me facilita el entorno de test de Redsys, por lo que queda confirmada que es genérica...

**Comment by DarkYamik** [comment]
Muchas gracias, era ese el problema.

Gracias por la ayuda y disculpen las molestias. :D
