### ISSUE TITLE
Problema con el padding de los zeros en Magento 1.8.1

### ISSUE THREAD

**Issue by Caradras** [DevopensourceTeam/Devopensource_Redsys#21]
Bueno, el módulo funciona pero tiene un par de errores, os dejo aquí el primero:

En la linea 83 del IndexController.php se añade un padding de zeros al ID de pedido:
$numpedido = str_pad($orderId, 12, "0", STR_PAD_LEFT);

Así el resultado (almenos para nuestros commerces en versión 1.8.1 de Magento) queda como 0001XXXXXXXX

Para solucionarlo hemos tenido que añadir, a la descodificación, en la linea 327 del IndexController.php (creo) hemos tenido que quitar el padding de zeros.
$order = Mage::getModel('sales/order')->loadByIncrementId($orde);
La solución rápida es multiplicar por 1 (PHP convierte el tipo de String a entero direcramente):
$order = Mage::getModel('sales/order')->loadByIncrementId($orde*1);
La solución elegante sería quitar los 3 ceros.

Sino quito el padding de ceros no hay forma de que me reconozca el pedido y genera un fallo del que solo te das cuenta si revisas el TPV (devuelve un 180 en las Notificaciones) o revisas los estados de los pedidos (no se actualizan a Processing) que se quedan en Pending.

Un saludo.
Carles.

**Comment by olivermontes** [comment]
Buenas @Caradras 

Veo que eres el mismo user de stackoverflow.com te comento:
- Este modulo no es el mismo que tiene Redsys en su pagina de descarga
- Utilizamos la misma RedsysAPI, pero tenemos pendiente de quitar la necesidad de usarla

Esa linea en el Controller de este modulo esta en blanco, vamos que no es el mismo.

```
$_order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);
```

Aqui lo que esta mal es la primera linea que se cambiara, que es lo mismo pero como tendría que ser

```
$_order = Mage::getModel('sales/order');
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);
```

**Comment by Caradras** [comment]
Hola @olivermontes exacto, soy el de StackOverflow, el mismo.

Tienes razón, no es la linea 327, sino la 301 (he vuelto a descomprimir el módulo para comprobarla), por eso puse el "creo". 
Después de los mil Debugs en el log, las lineas han corrido un poco.

Tengo la versión 2.8.3 de vuestro código, que se puede encontrar en:

http://www.redsys.es/wps/portal/redsys/publica/areadeserviciosweb/descargaDeDocumentacionYEjecutables/!ut/p/a1/jZBNC4JAFEV_jVvnaeFHuzHKFGsEKXU2oTCNgjqiU_79TNoEad3de5wDl4soShBtskfJM1mKJqteNzWuNrZ3mueCRyJDB-9yOuoBwUBCGIF0HnD35n8-zATDLz9GdEIOZOtqegS-azr26GmOA1EAoK_fwFLFCVjo4CPKK5FPe6S4yVcWR7RjN9axTr1347uQsu03CigwDIPKheAVU1mvwDejEL1EyQeI2vqcQBnWsdXjJ5rqlCw!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/

bajo:
Módulo de pago Magento v 2.8.3    10/11/15

**Comment by Caradras** [comment]
Veo que la solución que me das esta en la linea 42 y en la 470

En la linea 42 igualmente no "me" soluciona el problema ya que mi problema reside en la linea 79
$numpedido =  str_pad($orderId, 12, "0", STR_PAD_LEFT); 
que es cuando se cambia mi "numero" de pedido para ponerlo para el que supongo que es el estándar de la SHA256.

Mi codigo no pasa por la linea 459 ya que mis parámetros se pasan por POST y no por GET (linea 217)

Mi problema infiere en la linea 301 (por Post) o en la linea 459 (por Get) con el código:
$order = Mage::getModel('sales/order')->loadByIncrementId($orde);

Que intenta recuperar un $orde que no existe en mi base de datos ya que lleva los 3 zeros de padding delante.

Un saludo.

**Comment by olivermontes** [comment]
@Caradras 

**Siento insistir pero, no es el mismo módulo, este modulo esta en la version 0.1.4** 

Puedes verlo aqui https://github.com/DevopensourceTeam/Devopensource_Redsys/blob/master/app%2Fcode%2Flocal%2FDevopensource%2FRedsys%2Fetc%2Fconfig.xml

Vamos que el nuestro puedes descargarlo de este Github o mas facil http://redsys-magento.devopensource.com/ desde aqui

Por favor revisa esto que podemos estar mareando a alguien y no debemos :octocat:

**Comment by Caradras** [comment]
Siento mucho que sea así, el módulo está en la web de Redsys y en StackOverflow me has indicado que debería postear el problema en Este Foro...

Mil disculpas por marearos, no era la intención.

**Comment by olivermontes** [comment]
Buenas @Caradras 

Veo donde esta el error :+1: 

En mi respuesta me refiero que mejor uses este, lo hemos desarrollado por la falta de calidad del código del modulo de Redsys (el enlaces que nos comentas).

Mi recomendación es que utilices este ya que esta siendo testeado por mas de 35 tiendas ahora mismo y creciendo a buen ritmo

Vamos que esta hecho para ti, desarrollador como nosotros que ve poco fiable el modulo propuesto por Redsys

Saludos y Gracias!!

**Comment by Caradras** [comment]
si, te he entendido mal. Mil disculpas

**Comment by olivermontes** [comment]
No te preocupes @Caradras, pero lo veo importante ya que hemos pasado por lo mismo y por eso ahora estamos aqui.

Te invito a probar el modulo y colaborar con la comunidad :+1: 

Cierro el hilo.

Saludos
