### ISSUE TITLE
Problema con la creación de la Ds_Merchant_ProductDescription

### ISSUE THREAD

**Issue by Caradras** [DevopensourceTeam/Devopensource_Redsys#22]
Hola, aqui va otro problema.

Al crear el Ds_Merchant_ProductDescription se concatenan los nombres de los productos añadidos al carrito de Magento, hasta aquí bien.

El problema viene cuando (por desgracia) hay un producto que contiene algún símbolo "extraño" en su nombre. 
En nuestro caso nuestro cliente tenía un producto con un "%" en el nombre.
Lo que hacía que, probablemente por un problema de codificación, los datos que llegaban a Redsys fueran diferentes de su compresión, fallando siempre que este producto estaba en el carrito y generando un error antes de llegar a la pasarela.

La solución rápida para salir del paso (no la adecuada, pero si para que el cliente volviera a vender rápidamente) ha sido pasar un filtro para eliminar cualquier nombre con carácteres extraños justo debajo de la linea 75 debajo del FOREACH poner:

$productos = preg_replace('/[^A-Za-z0-9 ]/', ' ',$productos);

Esto puede generar nombres extraños de productos que contengan ç, ñ, o acentos.
Lo ideal sería pasar una función de normalización (en caso de querer adoptar esta solución) que traslade cualquier acento o carácter alfabético "extraño" a otro , quizás con unas listas de "STRTR"

La función ideal sería mirar qué ocurre con los símbolos extraños y porqué estos no se trasladan correctamente tras la codificación con SHA256.

**Comment by olivermontes** [comment]
Hola @Caradras 

El mismo caso que mi comentario anterior, pero esta vez no sabemos si puede pasar lo que comentas con nuestro modulo sobre el tema de los caracteres

Nuestra function sobre este punto comentado es este:

```
 public function getDescriptionOrder($_order){
        $descriptionOrder = '';
        $items = $_order->getAllVisibleItems();
        $pos = 0;
        foreach ($items as $itemId => $item) {
            $descriptionOrder .= $item->getName();
            $descriptionOrder .= " x " . $item->getQtyToInvoice();
            $pos++;
            if($pos<count($items)){
                $descriptionOrder .= " , ";
            }
        }
        return $descriptionOrder;
    }
```

Lo probaremos y te damos Feedback

Saludos!

**Comment by olivermontes** [comment]
Parece que estamos combinando hilos de Issues, cierro este continuamos en el otro
https://github.com/DevopensourceTeam/Devopensource_Redsys/issues/21

**Comment by Caradras** [comment]
Te comento lo mismo que en mi comentario anterior:

El sitio desde el que he descargado el código de Redsys:
http://www.redsys.es/wps/portal/redsys/publica/areadeserviciosweb/descargaDeDocumentacionYEjecutables/!ut/p/a1/jZBNC4JAFEV_jVvnaeFHuzHKFGsEKXU2oTCNgjqiU_79TNoEad3de5wDl4soShBtskfJM1mKJqteNzWuNrZ3mueCRyJDB-9yOuoBwUBCGIF0HnD35n8-zATDLz9GdEIOZOtqegS-azr26GmOA1EAoK_fwFLFCVjo4CPKK5FPe6S4yVcWR7RjN9axTr1347uQsu03CigwDIPKheAVU1mvwDejEL1EyQeI2vqcQBnWsdXjJ5rqlCw!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/

El nombre del enlace:
- Tienda Virtual Magento
- Módulo de pago Magento v 2.8.3    10/11/15

Y si, he comprovado que es la versión 2.8.3 en la linea 170:
$miObj->setParameter("Ds_Merchant_Module","magento_redsys_2.8.3");

Saludos!
Si no es vuestro módulo... Bueno, en su nombre pone Redsys, se descarga desde la web de Redsys...

**Comment by Caradras** [comment]
Siento que no sea vuestro módulo, desde Stackoverflow me has redirigido aquí.

PD: encantado de controbuir a vuestro proyecto.
