### ISSUE TITLE
Estado pedido, email confirmación compra

### ISSUE THREAD

**Issue by victol09** [DevopensourceTeam/Devopensource_Redsys#23]
Hola,

Antes de nada agradecerles dejar el modulo abierto, muchas gracias!! quería hacerles una consulta estoy probando el modulo el pago finaliza de forma correcta pero el estado del pedido OK dentro de magento siempre se queda en pendiente de pago y la plataforma no envia la confirmación del pedido al cliente ¿podrían ayudarme?

Un saludo y gracias de antemano.

**Comment by mbernabeu** [comment]
Hola @victol09 

Estas probando esto en un entorno local o algún entorno de desarrollo al que no se tenga accesso desde fuera o esta protegido por contraseña??

**Comment by victol09** [comment]
Hola @mbernabeu 

Es un entorno de desarrollo funcional 100%, no tiene protecciones de ningún tipo.

Gracias!!

**Comment by mbernabeu** [comment]
es multitienda o tiene https?

**Comment by victol09** [comment]
Ni multitienda ni https, jejejeje

**Comment by mbernabeu** [comment]
podrías enviarme la url de la tienda si quieres envíamela al correo marc.bernabeu@devopensource.com

**Comment by victol09** [comment]
Ok te envío los datos al email, te envío accesos del admin también :) ?

**Comment by mbernabeu** [comment]
no no es necesario

**Comment by victol09** [comment]
okis gracias!

**Comment by victol09** [comment]
Enviado Marc, gracias de nuevo!!

**Comment by mbernabeu** [comment]
Hola victor veo que me dices que apunte a un ip por vhost ese sera el problema que Redsys en el callback no reconocerá la dirección entonces el callback no llega por que redsys no reconoce esa direccion

**Comment by victol09** [comment]
Ok, entonces me aconsejas que lo pruebe en producción directamente?

**Comment by mbernabeu** [comment]
Yo lo que haría seria crear un subdominio por ejemplo dev.tudominio.com y apuntarlo al servidor de pruebas.

Pero si quieres probarlo en producción también tienes una opción que es subir el modulo, desactivar el método de pago y activar la opción de desarrollador del modulo

Luego indicar tu ip en el apartado de sistema/configuración/desarrollador/ips permitidas de esta forma solo tu veras el método de pago en producción para realizar pruebas

**Comment by olivermontes** [comment]
@victol09 sobre este ultimo punto que comenta mi compañero, estamos realizando la documentación para que quede claro a todos

saludos

**Comment by victol09** [comment]
entonces casi mejor espero @olivermontes  jejeje

Muchas gracias a los dos!
