### ISSUE TITLE
Estado de pedidos pendientes al volver de Redsys

### ISSUE THREAD

**Issue by luisestudioalfa** [DevopensourceTeam/Devopensource_Redsys#25]
Hola,

Muchas gracias por el esfuerzo que estáis haciendo para crear este módulo.

Estoy actualizando esta tienda con vuestro módulo, ya que el oficial no me ha ayudado mucho ( ni el módulo en si, ni el servicio técnico ). Y la cosa esta en que los pedidos llegan al TPV, pero el estado de los pedidos en Magento es siempre pendiente...

En las notificaciones de Redsys me sale : 

9915    Error   http://mysitioweb.com/redsys/index/callback

La tienda es multiidioma y en otra indicidencia que teníais abierta pone el otro usuario que lo solucionó con "store URL".

He probado a acceder a dos url distintas como poneis:

www.tudominio.com/es/redsys/index/callback    --------  Me devuelve a la pagina
www.tudominio.com/redsys/index/callback       ---------   Me sale un 404

¿Como puedo solucionarlo? ¿Modificando el custom callback?

Muchas gracias de antemano,
Luis.

**Comment by olivermontes** [comment]
Buenas @luisestudioalfa 

Si te devuelve a la home, es correcta www.tudominio.com/es/redsys/index/callback
al tener multi-tienda esa tendría que ser la correcta

Recuerda que:
- Tiene que estar accesible a internet para que los servidores de Redsys puedan enviar el Callback
- No tener protección Apache o similar en la tienda

Estamos trabajando para poder añadir una nueva funcionalidad que permite guardar las trasactions en la funcionalidad de Magento, otros metodos de pago como Paypal ya lo hacen

**Comment by luisestudioalfa** [comment]
Hola @olivermontes 

Muchas gracias por tu respuesta. 

He comprobado el acceso a internet por parte del servidor y esta correcto y apache no tiene protección, pero ahora mismo el callback esta apuntando a 

www.tudominio.com/redsys/index/callback

En la configuración del módulo tengo la opción de callback a "HTTP".  Como puedo hacer para que apunte a la dirección correcta? 

www.tudominio.com/es/redsys/index/callback

Muchas gracias.

**Comment by raulVerdugo** [comment]
Buenos días @luisestudioalfa 

Puedes customizar tu url para que apunte a esa dirección, en la configuración del módulo despliega las opciones de callback y selecciona "**Custom Callback**", esto te habilitará un campo justo bajo de "**Callback**" llamado "**Url Callback**" donde puedes poner la url que necesites.

Ten en cuenta que si es multitienda deberás configurar una url diferente para cada idioma, es decir:
- Si es en español: www.tudominio.com/es/redsys/index/callback
- Si es en otro idioma: www.tudominio.com/"idioma"/redsys/index/callback

Espero haberte ayudado, si tienes alguna duda más no dudes en preguntar.

Déjanos algún comentario en  http://redsys-magento.devopensource.com/ para seguir ayudando a que esto crezca.
