### ISSUE TITLE
1.9.0.1 No recibe informacion de respuesta de REDSYS ni envía mail de confirmación.

### ISSUE THREAD

**Issue by chrisklein00** [DevopensourceTeam/Devopensource_Redsys#30]
Antes de nada agradecer el desarrollo del módulo de manera open source.
Tras instalar el módulo en unas cuantas tiendas Magento con diferentes versiones me he encontrado varios errores.

En versiones 1.7.0 el onepagecheckout genera un error 500. Hay solución desactivando por código la función de test para desarrollador.

En versiones 1.9.0.1 Magento no recibe información de la transacción ni manda mail de confirmación del pedido al cliente. Únicamente muestra que el cliente entra en el TPV. 

No sé si alguien ha tenido estos problemas.

Un saludo.

**Comment by mbernabeu** [comment]
Si el problema de la 1.7.0 se soluciona en la version 0.1.4

y el callback puede ser que Redsys no pueda tener acceso a tu web bien por que este en un entorno local, protección apache, redirección de Magento, si tienes https que redsys no lo certifique como valido o que tengas multitienda y falte algo de configuración...

**Comment by chrisklein00** [comment]
Para dar algo más de información al respecto. El módulo está instalado en 3 tiendas Magento 1.9.0.1 y diferentes servidores. Está probado en un entorno de producción, no es multitienda, si disponen de certificado rapid SSL y la configuración creo que es correcta ya que he montado el módulo en otras tiendas con otras versiones de Magento y no he tenido ningún problema.

**Comment by mbernabeu** [comment]
pues entonces solo se me ocurre que Redsys no acepte el certificado rapid SSL, prueba modificando el callback y ponlo en Http

**Comment by chrisklein00** [comment]
Gracias por tu ayuda. Parece ser que no soporta el certificado Rapid SSL. Hay que modificar los parámetros de respuesta a Http en vez de Https.
