### ISSUE TITLE
Pedidos en estado "Pendiente" luego de procesarse el pago

### ISSUE THREAD

**Issue by maxxxiu** [DevopensourceTeam/Devopensource_Redsys#33]
Hola, 

En principio felicitarlos y agradecerles el gran trabajo que hacen para la comunidad. 

He remplazado vuestro modulo por el oficial de Redsys, pero quisiera preguntarles si tienen alguna idea del porque NO cambia el estado de los pedidos en nuestra tienda. Tanto como si se genera bien el pago o mal, siempre el estado del pedido queda “pendiente”. La configuración es correcta. 

No tengo una multitienda pero si tenemos varias vistas de tienda. 

Adjunto la config. del modulo.

Gracias! Saludos,

**Comment by santialsur** [comment]
Me pasa exactamente lo mismo, los pedidos hayan sido pagados correctamente en el tpv o no se quedan indicando "Pendiente": 
![screen shot 2015-12-22 at 10 15 59](https://cloud.githubusercontent.com/assets/16398834/11951960/5acb7fee-a895-11e5-82eb-bd2b0c5d32f9.png)

**Comment by jruzafa** [comment]
Puede que no llegue el callback de redsys y no los cambie a procesando, revisar que tiene acceso desde fuera y que la url del callback es correcta, ¿tienes multitienda?

**Comment by santialsur** [comment]
Hola! 

No hay multitienda, tienes razón con la url del callback no siendo accesible, pero creo que es algo a mejorar, te cuento, este es el log de $redsys en el redirectAction antes de codificarlo: 

2015-12-23T08:57:35+00:00 DEBUG (7): 2390
2015-12-23T08:57:35+00:00 DEBUG (7): RedsysAPI Object
(
    [vars_pay] => Array
        (
            [DS_MERCHANT_AMOUNT] => 2390
            [DS_MERCHANT_ORDER] => 201502418
            [DS_MERCHANT_MERCHANTCODE] => 312355481
            [DS_MERCHANT_CURRENCY] => 978
            [DS_MERCHANT_TRANSACTIONTYPE] => 0
            [DS_MERCHANT_TERMINAL] => 001
            [DS_MERCHANT_MERCHANTURL] => http://dev.xxxx.factoriadigitalpremium.es/redsys/index/callback
            [DS_MERCHANT_URLOK] => http://dev.xxxx.factoriadigitalpremium.es/index.php/redsys/index/success
            [DS_MERCHANT_URLKO] => http://dev.xxxx.factoriadigitalpremium.es/index.php/redsys/index/cancel
            [Ds_Merchant_ConsumerLanguage] => 001
            [Ds_Merchant_ProductDescription] => Titulo-Producto x 1
            [Ds_Merchant_Titular] => xxxxx
            [Ds_Merchant_MerchantName] => xxxxx
            [Ds_Merchant_PayMethods] => C
        )

)

En este caso el problema esta en la url que se mandaba: 
[DS_MERCHANT_MERCHANTURL] => http://dev.upsircesiv.factoriadigitalpremium.es/redsys/index/callback

El cliente se habia cargado el htaccess y aparte no usaba redirecciones web, no estaria de mas que esa url incluyera el index.php como las Url_Ko y Url_Ok quizas

**Comment by santialsur** [comment]
En efecto, ese era el tema, en cuanto configuro magento para dejar de usar /index.php/ en la ruta todo va ok:

23/12/2015 10:21:29|Procesando
Cliente No Notificado 
Pago TPV aceptado. (respuesta: 0000, autorizacion: 890585)

Como comentaba hay muchisimas instalaciones de Magento donde no se ha configurado asi, no estaria de mas añadir alguna comprobacion o el index.php a la url del callback

**Comment by maxxxiu** [comment]
Hola @santialsur ,

Podrías decirme como solucionar el problema? Como configuras magento para dejar de usar el index.php? Encontré una solución que habla sobre esto: http://www.hellothemes.com/es/blog-es/como-remover-index-php-de-tus-urls-magento/

Me puedes confirmar que es esto mismo lo que tu haz hecho?

Muchas gracias por tu ayuda. 

Un saludo,

**Comment by santialsur** [comment]
Hola @maxxxiu 

Si tienes el .htaccess que te da magento por defecto solo tienes que ir a sistema > configuración > web y cambiar usar reescrituras web a "si"

![screen shot 2015-12-23 at 14 40 54](https://cloud.githubusercontent.com/assets/16398834/11977458/63066978-a983-11e5-8038-168e1e538b42.png)

Saludos

**Comment by maxxxiu** [comment]
Hola @santialsur 

Desde ya, muchas gracias por tu ayuda, pero no lo he podido resolver, porque esa opción ya estaba activada, y según recuerdo el .htaccess creo que estaba modificado. 

Con lo cual la única forma de solucionarlo es como indica el link que te he pasado verdad? Que piensas?

Esto afectaría algo al resto del funcionamiento de Magento? 

Perdona por tantas preguntas, pero no soy un experto en Magento, y voy aprendiendo de a poco. 

Muchas gracias! Un saludo

**Comment by santialsur** [comment]
@maxxxiu no se si necesitas la primera parte de ese articulo, quiza con la modificación del htaccess te sirva por que el otro punto habla de urls seguras y no se si tendras un ssl habilitado 

Esta es la parte de rewrite del htaccess por defecto del magento 1.9.0.1: 

<IfModule mod_rewrite.c>

############################################

## enable rewrites

```
Options +FollowSymLinks
RewriteEngine on
```

############################################

## you can put here your magento root folder

## path relative to web root

```
#RewriteBase /magento/
```

############################################

## workaround for HTTP authorization

## in CGI environment

```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

############################################

## always send 404 on missing files in these folders

```
RewriteCond %{REQUEST_URI} !^/(media|skin|js)/
```

############################################

## never rewrite for existing files, directories and links

```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
```

############################################

## rewrite everything else to index.php

```
RewriteRule .* index.php [L]
```

</IfModule>

pruébalo así a ver

saludos

**Comment by santialsur** [comment]
Vaya, se pierde el formato, aqui: https://github.com/adam-paterson/magento-ce-1.9.0.1/blob/master/.htaccess.sample 

De la linea 110 a la 147

**Comment by maxxxiu** [comment]
Muchísimas gracias por la ayuda @santialsur , lo probaré y te digo algo. 
Desde ya, muy felices fiestas! Saludos,

**Comment by antrax131** [comment]
Hola,
Tengo este mismo problema he revisado las soluciones que proponeis y sigo con el error, he intentado ver el log de $redsys pero en la carpeta var/log no lo almacena ¿donde lo almacena?, ¿como reviso que llegue el callback de redsys?

**Comment by jruzafa** [comment]
Buenos dias @antrax131 , no tendrás esa carpeta porque o bien Magento no te lo ha creado porque no tienes activado el log o porque no tiene permisos, comprueba que tienes habilitado el log de Magento y si te la sigue sin crear creala tu a mano. 

Cuando llega el callback puedes comprobarlo porque mete un comentario de pedido en ese pedido, de todas formas para poder debugearlo mejor mete un Mage::log en la función callbackAction del fichero IndexController.php para saber que lo recibe.

Tambien comprueba que el callback pueda llegar a tu entorno.

**Comment by antrax131** [comment]
He revisado la carpeta var/log y esta ok recibo sin problemas cron.log, exception.log, system.log voy a probar a crear el archivo "redsys.log" a ver si asi recibo algo, ¿seria este el nombre?
Ahora recibo esto en frontend
![sin titulo-1](https://cloud.githubusercontent.com/assets/7694977/12230441/e73bf2f4-b850-11e5-9dbe-ea514f8a68f3.jpg)
Antes recibia esto
![sin titulo-2](https://cloud.githubusercontent.com/assets/7694977/12230460/08fb7d1a-b851-11e5-943f-f43fe395c55c.jpg)

**Comment by antrax131** [comment]
Una duda mas mi tienda esta configurada asi un dominio .com con 3 idiomas + dominios territoriales ¿hay que hacer alguna configuración especifica en redsys?

**Comment by antrax131** [comment]
Sigo con el problema del cambio de estado, he intentado resolverlo siguiendo estos pasos:
1. Revisar el rewrite en htaccess
2. quitar /index.php/ de las url en el admin
3. activado el log y creado a mano el archivo "redsys.log"
4. revisados los permisos de escritura en "redsys.log"
5. tenemos certificado ssl he probadado a seleccionar el cllabac con http y https no recibimos el callback.
¿que mas puedo revisar? no se si leiste mi anterior mensaje, ¿es correcto el nombre de "redsys.log"?

**Comment by danielozano** [comment]
Quizás sea una pregunta un tanto estúpida pero, dentro del TPV de redsys tienes activa la opción de URL en los parámetros.

**Comment by santialsur** [comment]
@antrax131 imagino que cuando hablas de redsys.log lo que intentas es recibir los datos que mostraba arriba, si es lo que buscas, tendrás que editar: app/code/community/Devopensource/Redsys/controllers/IndexController.php

Despues de la linea (linea 50):  
$redsys->setParameter("Ds_Merchant_PayMethods", $payMethods);

Añade:  
Mage::log($redsys,null,'redsys.log',true);

Ahora volcaras el objeto $redsys a ese archivo de log cada vez que vayas a salir de tu web hacia el tpv, mientras no lo indiques no pasara (tu situación actual), fijate en la forma de indicar a magento que quieres logear algo y anotala por que te sera util 

Sobre este punto: 2. quitar /index.php/ de las url en el admin 
Lo que importa es que las urls del frontend no usen /index.php/

Cuando tengas el volcado del objeto pegalo por aqui a ver que dice

**Comment by antrax131** [comment]
Creo que el error esta dentro del TPV de redsys adjunto la imagen de como esta configurado.
Sobre el punto 2 ya tenia quitado /index.php/ en el frontend y ahora tambien lo he quitado del admin.

![sin titulo-3](https://cloud.githubusercontent.com/assets/7694977/12350676/c2a86690-bb78-11e5-8163-ad509a8fa073.jpg)

**Comment by santialsur** [comment]
@antrax131 la verdad no lo se, el cliente nunca me paso acceso a esa parte, el caso es que imagino que los datos que salen de magento deben coincidir con los que tengas ahi definidos

**Comment by antrax131** [comment]
la verdad esque antes con esta configuración me ha funcionado, no estoy seguro si ahora hay que rellenar la url de notificación, url ok, url Ko

**Comment by danielozano** [comment]
Esa información (las URLs KO y OK) ya la envía la extensión. Pero si eres capaz de pasar de Magento al TPV de forma correcta, rellenas los datos y al volver es cuando no sucede nada el problema está en Magento.

Intenta generar un log en la callbackAction de la extensión.

_Línea 72: Devopensource/Redsys/controllers/IndexController.php_

``` php
   public function callbackAction()
    {
        Mage::log('Funciona', null, 'redsys.log');
```

Luego realiza una prueba y ve a **var/log** busca **redsys.log**, si existe y tiene esa frase es que la vuelta se hace de forma correcta pero algún parámetro es incorrecto y podremos seguir debugueando.

**Comment by antrax131** [comment]
He probado a generar el log como indicas y no manda nada, he hecho 3 pruebas difrentes y el resultado es el mismo. 
Una de ellas a sido cambiando  "Estado para pedido al entrar en TPV : Redsys pago realizado"
Tambien he visto que no genera las facturas automaticamente.

**Comment by danielozano** [comment]
Pues creo que el problema reside en que no se está ejecutando la función callbackAction, si te parece vamos a debuguear las dos que si se te están ejecutando: successAction y cancelAction

**Línea 148: Devopensource/Redsys/controllers/IndexController.php**

``` php
    public function cancelAction()
    {
        Mage::log(print_r($_POST, true), null, 'redsys.log');
```

**Línea 180: Devopensource/Redsys/controllers/IndexController.php**

``` php
    public function successAction()
    {
        Mage::log(print_r($_POST, true), null, 'redsys.log');        
```

Estas URL son la URLKO Y URLKO, es decir cuando se muestran el mensaje en tu portal de pedido realizado o pedido cancelado por redsys.

Las facturas creo que no las genera por que no ejecuta callbackAction.

Como resultado de esto deberían llegarte los parámetros de Ds_Signature y Ds_Merchantparams si no recuerdo mal.

Muchas gracias, un saludo.

**Comment by radov3r** [comment]
A mí me ha pasado igual, pero mi problema era tan tonto como que estaba en un servidor local y la web era inaccesible desde fuera... Por si le ayuda a alguien!

**Comment by antrax131** [comment]
Esto es lo que he recibido en el redsys.log, activando las dos que si se te están ejecutando: successAction y cancelAction

2016-01-24T12:50:35+00:00 DEBUG (7): Array
(
)

Gracias Radov pero es una tienda activa.

**Comment by danielozano** [comment]
Ok, pues estoy KO. Creo que lo mejor es comprobar que las sobreescrituras de url funcionan correctamente.

Para asegurarnos en la función callbackAction(), línea 144

``` php
}else{
    Mage::log('Im here', null, 'redsys.log');
    $this->_redirect('');
}
```

Si intentas acceder a http://www.tutienda.com/redsys/index/callback y te da error 404 quiere decir que la sobreescritura no está funcionando, por lo que nunca se ejecuta el callback.

Si esto te da 404 y pruebas http://www.tutienda.com/redsys/index.php/index/callback y te sigue dando error 404, supone un problema ya que esto significa que hay algún tipo de error con esta URL. Si por el contrario te redirige a la homepage significa que simplemente tenemos que solucionar lo de las sobreescrituras.

Si esta última URL no te funciona, quizás es que tienes instalada alguna extensión que está pisando la URL.

**Comment by antrax131** [comment]
recibido en el redsys.log con la función callbackAction(), línea 144
2016-01-24T19:05:12+00:00 DEBUG (7): Array
(
)

http://www.tutienda.com/redsys/index/callback  se va a la home page
http://www.tutienda.com/redsys/index.php/index/callback   File not found.

**Comment by danielozano** [comment]
Disculpa, me equivoqué al escribir la segunda petición que debería ser: http://www.tutienda.com/index.php/redsys/index/callback puse el index.php donde no debía, pero si te ha funcionado la primera, te funciona bien la segunda y quiere decir que la sobreescritura de urls funciona correctamente.

La única conclusión a la que llego es que redsys no hace una petición a dicha URL, y simplemente redirecciona de vuelta a la URL KO/OK.

El parámetro dentro del TPV de Redsys: host (URL) concuerda con el host de tu tienda verdad. Sé que es una tontería pero de momento no se me ocurre nada más.

**Comment by r4y7s** [comment]
He encontrado un problema que hacia que la url de callback diera un 404

si esta activo la opcion de código de tienda en las url
![image](https://cloud.githubusercontent.com/assets/6150209/13292596/a6caa6d6-db1c-11e5-91dc-9ffb445e1cb6.png)

la url de construye como: http://www.tutienda.com/redsys/index/callback cuando debería ser por ejemplo http://www.tutienda.com/es_es/redsys/index/callback y por este motivo nunca resuelve el callback

Yo temporalmente lo que he hecho es editar el archivo
/app/code/community/Devopensource/Redsys/Helper/Data.php
y remplazar linea 33:
return Mage::getStoreConfig('web/unsecure/base_url', Mage::app()->getStore())."redsys/index/callback";
por
return Mage::getBaseUrl() . 'redsys/index/callback'; 

y la linea 35 cambiarla por:
return Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'redsys/index/callback';

Saludos

**Comment by juandiegojr** [comment]
Habéis avanzado algo? Me estoy muy atento, ya que me encuentro exactamente con el mismo problema. Pedido realizado, pagado, me redirige bien al OK pero sigue en pediente y el total del pedido en adeudado.

![image](https://cloud.githubusercontent.com/assets/16169562/13764514/41a0e322-ea50-11e5-8194-cd9860f3582f.png)

El htaccess está ok y las sobreescrituras

Tanto /redsys/index/callback como /index.php/redsys/index/callback me mandan a la home
1 tienda con 2 vistas de idioma y sin codigo en la URL de las tiendas.

Un saludo y gracias por todo

**Comment by juandiegojr** [comment]
Buenas,

Chicos por lo menos en mi caso, por casualidad acabo de encontrar el problema: Cloudflare
Leyendo por foros, he pausado el servicio y lo ha hecho todo correctamente.

Revisando parece que el problema está en desactivar el **browser integrity check** en el servicio.
Espero haber podido ayudar a alguien con esto.
Un saludo!

**Comment by maxxxiu** [comment]
Hola @juandiegojr ! 

Yo fui el que escribió el primer post, y hasta hoy, no lo había podido solucionar, y tu respuesta fue la correcta para solucionar mi incidencia. También tengo **Cloudfare** en mi tienda, y había intentado hace tiempo de desactivar todo **cloudfare**, pero no había funcionado, con lo cual deben haber tenido un bug que dejaba activada esa opción en particular. Ahora desactive lo que tu has dicho, y funcionó! 

Gracias por la ayuda, y esperemos que les ayude a otros que tienen el mismo problema. 

Saludos. 

PD: Cierro el Post, ya que fue solucionada la incidencia.

**Comment by jpefranco** [comment]
Hola, tengo un problema en la web https://www.artglobale.com, que usa Magento y Cloudflare. Para la configuración de Cloudflare esta desactivado browser integrity check, habilitado https como Full (SSL) y tres reglas:

*artglobale.com/redsys* -> Disable Security        
(si deshabilito esta regla, magento no notifica correo y el estado se queda en pending, así que parece que el TPV RedSys quiere que la url de retorno sea por http, en lugar de https)

*artglobale.com/checkout* -> Disable Security

http://www.artglobale.com/* -> Always use HTTPS

En Magento, tanto en parte Segura como Insegura tengo configurada la variable:
URL Base = https://www.artglobale.com/

El problema lo tengo en el proceso de compra, que aunque notifica los mail y el estado es el correcto, no se queda en la página que indica al usuario que el pedido se ha realizado correctamente, sino que me lleva a la HOME. 

http://www.artglobale.com/redsys/index/callback -> Te lleva a la HOME
http://www.artglobale.com/index.php/redsys/index/callback -> Genera un error 404

¿Qué faltaría por configurar para que funcione correctamente el ciclo de compra completo?

Gracias,
Jesús

**Comment by olivermontes** [comment]
Buenas @jpefranco por reglas de Cloudflare por algún motivo nunca no funciono de manera real, mejor no lo utilices ya que quitar el SSL del checkout es algo que no te recomiendo

Si la URL te redirecciona a la HOME es la correcta

El truco como indicas arriba es enviar el callback de Redsys fuera de HTTPS, por que? por que no valida cualquier certificado la comunicación que envia Redsys un poco triste 😢 

subiremos cambios para poder "solventar" este problema

Saludos

**Comment by antrax131** [comment]
Yo solucione los problemas con Resys con estos Cipher:

ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS

**Comment by jpefranco** [comment]
Hola antrax131, puedes indicar donde y como se configura el Cipher que comentas pls.

**Comment by albert-elcorriol** [comment]
@olivermontes ¿tenéis ya adaptado el módulo para Magento 2.1? Tengo un problema con el HTTPS y el módulo que me proporciona Redsys con el certificado (són muy restrictivos con el certificado, y para cumplirlo hay que comprar un certificado muy caro). Con lo que estoy evaluando de hacer lo que dices, enviar la petición a Redsys sin http, para evitar el problema de certificado. ¿Sabes como puedo hacerlo con Magento 2?

**Comment by jan1980** [comment]
+1, yo también estoy interesado en saber cómo podemos recibir el callback por http (en vez de httpS) -si eso fuera una solución adecuada- para que nos actualice el estado del pedido a Completado... ¿Cómo hacerlo? Mil gracias por cualquier ayuda.
