### ISSUE TITLE
Importe sin asignar

### ISSUE THREAD

**Issue by cfaria** [DevopensourceTeam/Devopensource_Redsys#35]
Hola equipo!

Mirad, estaba haciendo una prueba del módulo para ponerlo ya en real y cuando realizo el pedido me sale lo siguiente en Redsys: 

![captura de pantalla 2016-01-14 a las 13 31 01](https://cloud.githubusercontent.com/assets/756658/12324569/c459626a-bac3-11e5-8408-c7a9c14186fc.png)

El pedido se crea correctamente en Magento pero por lo visto los datos no llegan bien a Redsys, con lo que no se puede realizar el pago.

¿Sabéis que puede pasar? ¿Reinstalo el módulo?

Por cierto, es un Magento 1.9.1.0 con todos los parches de seguridad hasta la fecha instalados.

Gracias!

**Comment by cfaria** [comment]
Por cierto, las pruebas en el entorno de test las hizo perfectamente. Raro raro.

Muchas gracias! Sois unos cracks ;D

**Comment by olivermontes** [comment]
Buenas Carlos!

Mira esta documentación para ver el código de Error o tambien el email que envia Redsys si tienes acceso al email de configuración donde envían las notificaciones

https://github.com/DevopensourceTeam/Devopensource_Redsys/wiki/C%C3%B3digos-de-error-de-TPV
Ya nos comentas

**Comment by cfaria** [comment]
Que documentación? Me pasas url?

**Comment by olivermontes** [comment]
https://github.com/DevopensourceTeam/Devopensource_Redsys/wiki/C%C3%B3digos-de-error-de-TPV

**Comment by cfaria** [comment]
OK, el error que muestra es el siguiente:

SIS0042: La firma enviada no es correcta.

Voy a comprobar que es correcta la firma y os digo. A ver si es que soy yo torpe o que.

Gracias Oliver. ;)

**Comment by cfaria** [comment]
Listo! Fallo mio, el problema estaba en el nombre del comercio, lo tenía mal puesto y por tanto se generaba incorrectamente la firma.

Gracias por todo Oliver.
