### ISSUE TITLE
¿Error en la libreria RedsysAPI?

### ISSUE THREAD

**Issue by PacoCalvo** [DevopensourceTeam/Devopensource_Redsys#36]
Hola.
Tengo un magento 1.9.2.2 multitienda multidominio sobre PHP 5.5. Al instalar el módulo de Redsys, la web se cae y muestra esta pantalla. Ocurre lo mismo con la extensión Excellence_redsys. No está compilada, ni tiene la caché activada. ¿Alguna idea?

Gracias.

Warning: include(PEAR/Error.php): failed to open stream: No such file or directory  in /var/www/vhosts/xxxxxxxxxx.es/httpdocs/lib/Varien/Autoload.php on line 94
#0 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(PEAR/Er...', '/var/www/vhosts...', 94, Array)
#1 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/lib/Varien/Autoload.php(94): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('PEAR_Error')
#3 [internal function]: spl_autoload_call('PEAR_Error')
#4 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/lib/Redsys/json.php(779): class_exists('PEAR_Error')
#5 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/lib/Redsys/apiRedsys.php(24): include('/var/www/vhosts...')
#6 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/app/code/community/Devopensource/Redsys/controllers/IndexController.php(3): require_once('/var/www/vhosts...')
#7 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(337): include('/var/www/vhosts...')
#8 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(308): Mage_Core_Controller_Varien_Router_Standard->_includeControllerClass('/var/www/vhosts...', 'Devopensource_R...')
#9 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(196): Mage_Core_Controller_Varien_Router_Standard->_validateControllerClassName('Devopensource_R...', 'index')
#10 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/vhosts/xxxxxxxxxx.es/httpdocs/index.php(107): Mage::run('xxxxxxxxxx', 'website')
#14 {main}

**Comment by olivermontes** [comment]
Si es por que utilizamos la libreria de Redsys que quitaremos pronto.

Esta la issues creada https://github.com/DevopensourceTeam/Devopensource_Redsys/issues/9 https://github.com/DevopensourceTeam/Devopensource_Redsys/issues/9

es un Warning, no tendría que mostrarse en frontend si tienes el #ini_set('display_errors', 1); comentado en tu index.php

saludos

**Comment by PacoCalvo** [comment]
gracias.

Enhorabuena por el trabajo.

Francisco Calvo Savall | CEO & Director Técnico | paco@magrana.net

MAGRANA CREATIVITAT DIGITAL, S.L. :: http://www.magrana.net
Sant Francesc, 3 :: 03510 Callosa d'en Sarrià (Alicante) :: Tel. 965 88 08 61

AVISO LEGAL Este mensaje electrónico está dirigido únicamente al destinatario designado. Su carácter personal, confidencial e intransferible está protegido legalmente. Cualquier revelación, uso o reenvío no autorizado, total o parcial, está prohibida. Si ha recibido este mensaje por error, rogamos lo notifique de inmediato a la persona que lo remite y borre el mensaje original junto con sus ficheros anexos sin leerlo ni grabarlo, total o parcialmente. En cumplimiento de la Ley de Servicios de la Sociedad de la Información y de correo Electrónico y, de la Ley Orgánica sobre Protección de Datos, le comunicamos que su dirección de correo electrónico forma parte de un fichero automatizado con la finalidad de prestarle los servicios de comunicación comercial o informativa. Si lo desea puede ejercer sus derechos de acceso, rectificación, oposición y cancelación de sus datos, dirigiéndose por escrito a Francisco Calvo Savall., C/ Sant Francesc, 3, 03510 Callosa d’en Sarrià, Alicante, o mediante correo-e a la dirección  central@magrana.net
