### ISSUE TITLE
Enhorabuena

### ISSUE THREAD

**Issue by AbrahamMartinLopez** [DevopensourceTeam/Devopensource_Redsys#39]
Muchas felicidades.
Probé con la versión de Redsys original para magento y no daba más que errores, con vuestro API va genial.
Un saludo desde Madrid.

**Comment by olivermontes** [comment]
Genial @AbrahamMartinLopez tambien parte es de la comunidad que nos ayuda al desarrollo y comprobaciones

Saludos
