### ISSUE TITLE
No aparece método de pago

### ISSUE THREAD

**Issue by guillermogallego** [DevopensourceTeam/Devopensource_Redsys#42]
Me ha sido imposible que en la pantalla donde el cliente opta por el método de pago con el que desea pagar me aparezca la opción de la tarjeta de crédito.

He seguido las instrucciones de instalación y configuracion

Hay algo que hacer diferente en caso de utlizar una plantilla comprada ?

Espero pueda ayudarme
Gracias

**Comment by olivermontes** [comment]
Tienes que dejar solo este modulo en tu tienda, no tengas habilitados otros módulos de TPV de Redsys puede ser ese tu conflicto

**Comment by guillermogallego** [comment]
Tenia habilitado el oficial pero no me funciono y luego borre todos los 
archivos de ese modulo

Voy a hacer una copia limpia y les cuento

Gracias

**Comment by guillermogallego** [comment]
No hay manera, lo instalé en una copia que nunca se le habia instalado otro modulo redsys y tampoco muestra la opción de pago

http://www.nataciondeportiva.com/csorder/multishipping/billing/

Te dejo la url por si se te ocurre por donde puede estar el problema

**Comment by jruzafa** [comment]
¿Te tira algo en el var/log o var/report? Puede que te influya tambien la plantilla de shipping_method.phtml si esta tocada.

**Comment by jan1980** [comment]
Hola chicos, lo intenté instalar siguiendo las instrucciones pero me daba una pantalla en blanco en Configuración > Métodos de Pago (con el gratuíto original de RedSys desactivado, es decir, puesto en modo false en el .xml).

Total, he desactivado el vuestro, le he borrado todos los archivos, y estoy intentando volver al original de RedSys pero ya no me sale en el frontend como método de pago (sí me sale en el backend y actualiza, pero no en el frontend, dónde me salen los demás métodos de pago activados pero ya no el de RedSys).

Prefiero usar el vuestro ya que nos permite escoger cómo regresa, si en htttp o httpS, pero ahora no logro usar ni uno ni otro.

¿Sabéis cómo puedo recuperar el antiguo módulo? ¿Qué puede provocar que ya no me salga como método de pago?

¿Y lo de la pantalla en blanco, os lo han reportado alguna vez?

Edito: tengo esto en system.log:

```
2016-10-07T19:15:44+00:00 ERR (3): Warning: include(Excellenceredsys/Redsys/Model/Adminhtml/Enviroment.php): failed to open stream: No such file or directory  in /var/www/vhosts/nuestraweb.com/lib/Varien/Autoload.php on line 94

2016-10-07T19:15:44+00:00 ERR (3): Warning: include(): Failed opening 'Excellenceredsys/Redsys/Model/Adminhtml/Enviroment.php' for inclusion (include_path='/var/www/vhosts/nuestraweb.com/app/code/local:/var/www/vhosts/nuestraweb.com/app/code/community:/var/www/vhosts/nuestraweb.com/app/code/core:/var/www/vhosts/nuestraweb.com/lib:.:/opt/plesk/php/5.4/share/pear')  in /var/www/vhosts/uniquebrand.ovh.net/nuestraweb.com/lib/Varien/Autoload.php on line 94
```

Mil gracias y saludos,

**Comment by mbernabeu** [comment]
Hola @jan1980 

Esto ocurre por que por casualidad tenemos el mismo code del modulo y Magento no sabe en que carpeta esta, te recomiendo que en lugar de desactivarlo borres directamente los ficheros o tambien puedes probar renombrando la extension de .xml a .xml_old en lugar de poner a false ya que aunque le indiques que esta a false Magento sigue cargando el archivo y no olvides después de esto limpiar cache y compilación si la tienes habilitada.

**Comment by jan1980** [comment]
Ha funcionado perfectamente! Muchísimas gracias. Saludos,
