### ISSUE TITLE
Error en la instalación

### ISSUE THREAD

**Issue by develmedia** [DevopensourceTeam/Devopensource_Redsys#43]
Al instalarlo sobre magento 1.9.2.4 da error al vaciar la caché

Entiendo según el error, es que no crea la tabla.

a:5:{i:0;s:207:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nombrebasededatos.devopen_notification' doesn't exist, query was: SELECT `main_table`.\* FROM `devopen_notification` AS `main_table` WHERE (`is_read` = '0')";i:1;s:5127:"#0 /usr/home/0OqSk42sYRBZ/midominio.com/web/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)

**Comment by jruzafa** [comment]
Ese error se produce porque intenta acceder a esa tabla y no está instalada, prueba con borrar de la tabla **core_resource** la tupla "**devopennotify_setup"**, vaciar caché  y refrescar front o admin, ya te la tendria que crear

**Comment by mvivas** [comment]
@jruzafa yo tengo el mismo problema que @develmedia 

No encuentro la entrada que indicas en core_resource; por lo que no sé cómo proceder. Me puedes dar alguna indicación?

**Comment by jruzafa** [comment]
@mvivas entonces tiene pinta de que no se haya instalado el modulo de Notification, bajate cambios y prueba a instalarlo de nuevo.

**Comment by olivermontes** [comment]
no reply
