### ISSUE TITLE
E-mail de confirmación de compra no me llega con https

### ISSUE THREAD

**Issue by Robertuybrush** [DevopensourceTeam/Devopensource_Redsys#45]
Hola!

En primer lugar, muchas gracias por el módulo! Lo he instalado en varias tiendas y va como la seda.
Pero esta vez tengo un problemilla, que supongo que será debido a un problema mío de configuración, pero me gustaría que me ayudárais a encontrar la respuesta.

Cuando instalé el módulo en la web en cuestión, no tenía https y el e-mail de confirmación de pedido estaba llegando correctamente. Hace poco le pusimos el https y el e-mail no se envía, quedando además el estado del pedido en "Pending" en lugar de en "Processing".
Al principio pensaba que era porque el valor de la variable "Callback" estaba en "http", pero al cambiarlo a "https" me pasa lo mismo.

¿Será que la dirección del callback está mal? ¿Cómo puedo saber cuál es la correcta? ¿Se debe cambiar algo en el panel de administración del TPV al pasar la web a funcionar con https?

Muchas gracias!

**Comment by mbernabeu** [comment]
Hola @Robertuybrush 

Si antes funcionaba y ahora no puede depender de quien certifique el https nos ha pasado alguna vez que algunos certificados redsys no los considera validos y por eso no llega el callback.

**Comment by danielozano** [comment]
Hola @Robertuybrush 

¿Puedes mirar las notificaciones dentro del tpv (en el apartado Notificación dentro de redsys)?

¿Hay errores cómo este? **No trusted certificate found.**

Si es así dentro del módulo cambia a custom callback o metele http otra vez y ponte en contacto redsys.

**Comment by Robertuybrush** [comment]
Hola @mbernabeu y @danielozano

Efectivamente, me han pasado el acceso al admin del TPV que daba problemas y hay errores en la notificación que dicen **No trusted certificate found**, así que lo hablo con Redsys.

¡Muchas gracias de nuevo!

**Comment by danielozano** [comment]
@Robertuybrush  genial, si no te importa y puedes compartir la conclusión a la que llegues te lo agradecería bastante ya que me interesa el resultado.

¡Gracias !

**Comment by epmunoz** [comment]
Hola @Robertuybrush me pasa exactamente lo mismo, el pago se realiza correctamente, pero el pedido no se actualiza... He mirado en RedSys y mi certificado sí que está validado.  ¿habéis encontrado alguna solución?

**Comment by jomavazquez** [comment]
Hola,

A mí me pasa exactamente igual. Acabo de cambiar la web a https (usando el certificado ssl de comodo), he mirado el listado de certificados compatibles con redsys y sí está. El caso es que viendo mi panel de control de redsys veo que el callback se hace desde http, y claro, da un 301.

Por algún motivo, creo que el módulo no recoge bien este parámetro (aunque en sistema -> configuración haya puesto callback = https)

¿Tenéis alguna pista?

**Comment by mbernabeu** [comment]
Hola @jomavazquez 

Comprueba que en URL segura de Magento tienes https en la url.

**Comment by jomavazquez** [comment]
Hola @mbernabeu 

![captura](https://cloud.githubusercontent.com/assets/4919867/16108151/c5b1ffd0-33a1-11e6-8959-074cd7bdd8e0.PNG)

Claro, es lo primero que cambié. Cuando no tenía el certificado SSL funcionaba perfectamente. Fue cambiarlo y dejar de funcionar. Esta es el aviso que recibo desde mi panel de control de redsys:

![captura2](https://cloud.githubusercontent.com/assets/4919867/16108179/fcacb8f4-33a1-11e6-9c0f-7b3ead036d2a.PNG)

Al hacer el cambio de servidor, aproveché para migrar a php 7, eso sí, con el módulo de Inchoo y algunas correcciones extra. Con este cambio, vuestro fichero json.php de la carpeta lib tenía una estructura deprecated que también se arregla fácil. El caso es que ahora no hay ninguna excepción en el log.

**Comment by jomavazquez** [comment]
De hecho, @mbernabeu tanto en secure como en unsecure tengo https

![captura](https://cloud.githubusercontent.com/assets/4919867/16108281/87ded79a-33a2-11e6-8e70-d1daacc7a019.PNG)

**Comment by jomavazquez** [comment]
Bueno, después de poner a mano el ds_merchant_url, ahora resulta que (siendo los ficheros los mismos) https://www.conjuntados.com/redsys/index/callback me da un 404 como un demonio

**Comment by jomavazquez** [comment]
¡Solucionado!

**Comment by mbernabeu** [comment]
Hola @jomavazquez 
Podrias indicar cual era el problema por si otros usuarios se encuentran en el mismo caso

**Comment by jomavazquez** [comment]
Hola @mbernabeu pues al final la caché del sistema estaba fastidiando el asunto bastante. La caché y la función getUrlStore del helper, que por lo que sea no me estaba cogiendo bien la url con https. Lo que he hecho ha sido:

**Ir al controlador** (IndexController.php), y en la función pública redirectAction(), comentar la línea 

$urlStore = $this->helper->getUrlStore();

**Añadir las siguientes:**

$urlStore = Mage::getStoreConfig('web/secure/base_url', Mage::app()->getStore());

$locale = Mage::app()->getLocale()->getLocaleCode();

$locale = str_replace("_ES", "", $locale);

$locale = str_replace("_US", "", $locale);

$locale = str_replace("_DE", "", $locale);

$urlStore .= $locale."/redsys/index/callback";

Las líneas con $locale es porque no me estaba cogiendo la url correcta con el idioma de mis vistas (y tantos replace porque la tengo en esos tres idiomas).

**Reiniciar tanto nginx como php**

service nginx restart

service php-fpm restart

**Vaciar la caché externa** (última opción) en el backend -> sistema -> gestor de la cache

Listo! con eso ya me vuelve a funcionar correctamente.
