### ISSUE TITLE
Duplica el contenido del carrito al cancelar en el TPV

### ISSUE THREAD

**Issue by antoniolite** [DevopensourceTeam/Devopensource_Redsys#48]
En las pruebas que he hecho, al cancelar en el TPV, vuelve a la tienda duplicando las cantidades de los productos que había en el carrito. Si tenía 1 unidad de un producto, al volver hay 2.

**Comment by dtamajon** [comment]
Confirmo este comportamiento en nuestra instalación.

**Comment by mbernabeu** [comment]
Creo que esto se soluciono en el commit e61aec8228aea2670985e3655f73323ada2c06de ya que no ha vuelto a suceder.
