### ISSUE TITLE
DUDAS en comparación con el módulo antiguo de Servired

### ISSUE THREAD

**Issue by evuska** [DevopensourceTeam/Devopensource_Redsys#5]
Hola,
Lo primero MUCHAS GRACIAS POR COMPARTIR VUESTRAS MEJORAS..
Tenéis toda la razón en que la organización del módulo de Redsys ¡asusta!

Tengo un módulo muy antiguo de Servired y en él podía indicar el campo merchanturl en vuestra extensión ya no, ¿ por qué? ¿qué consecuencias tiene esto?

Desde el panel de administración de Redsys podemos configurar las url ok y url ko. En la imagen os muestro como son las url actuales. Usando vuestra extensión que debería poner??
.../redsys/index/cancel y 
.../redsys/index/success????

![servired2](https://cloud.githubusercontent.com/assets/15898559/11227874/12770622-8d89-11e5-88d7-511683d9379e.jpg)
![servired1](https://cloud.githubusercontent.com/assets/15898559/11227875/127f2050-8d89-11e5-8d5d-8ae8f55493f6.jpg)

**Comment by mbernabeu** [comment]
Hola en cuanto al UrlOK y UrlKO el modulo ya indica a Redsys donde debe recibir la llamada con lo cual creo que simplemente dejándolo vacío debería funcionar pero en caso contrario

Url OK:  http://www.tutienda.com/redsys/index/success
Url KO:  http://www.tutienda.com/redsys/index/cancel

Y el Url del Comercio es donde Redsys responde con el callback enviando la notificación como que el pago a sido recibido correctamente para modificarlo en el campo Callback debes seleccionar "Custom Callback" veras que se desplega un campo justo debajo llamado "Url Callback" ese campo es el Url de comercio.

![captura de pantalla 2015-11-18 a las 8 30 14](https://cloud.githubusercontent.com/assets/6458310/11235176/6d51e4fe-8dcf-11e5-8e3f-ed81fe652b14.png)

![captura de pantalla 2015-11-18 a las 8 30 22](https://cloud.githubusercontent.com/assets/6458310/11235183/75519fbe-8dcf-11e5-9fd8-16e42f77ecae.png)

Pero de todas formas si no tienes necesidad de modificar ese campo no lo modifiques déjalo en http o https en función de tu necesidad si no puede ser que deje de funcionar las notificaciones.

**Comment by olivermontes** [comment]
Te hemos podido solventar @evuska la duda?

**Comment by rvaquerizo117** [comment]
Hola,

Enorabuena por la iniciativa de desarrollar este módulo, hacía falta en Magento un módulo así.

Estoy teniendo problemas con los cambios de estados de los pedidos y parece que es por el callback.

He probado con secure, unsecure y custom {{secure_base_url}}es/redsys/index/callback, añadiendo el directorio del idioma. Esto último no se si es correcto, pero es como me funcionaba en otro módulo de servired, pero creo que este módulo tenía un bug, y este "apaño" lo hacía funcionar en tiendas multiidioma.

El caso es que todos los pedidos, sean completados o no los deja en pending teniendo estos valores:

Nuevo estado del pedido: Pendiente
Estado para pedido al entrar en TPV: Pendiente
Estado para pedido cancelado por redsys: Cancelado
Estado para pedido validados por redsys: Preparación

Por cierto, en la plataforma de redsys: la notificación Online HTTP + email comercio, ¿Que quiere decir?, ¿solo enviará la notificación del callback si está en unsecure?.

**Comment by mbernabeu** [comment]
Hola,

Tienes algún tipo de restricción por apache o redirección de algún tipo en tu web? en ese caso deberas quitarla para poder recibir el callback correctamente

En principio si en cada website o vista de tienda tienes indicado el base_url con el /es no seria necesario añadirlo al callback puedes enviarme una captura de esa parte de la configuración si quieres que te indique cual seria la forma correcta en tu caso. puedes encontrar esa configuración en sistema/configuración/web/Inseguro y Seguro.

El tema de los estados de pedido no se modifican por que no esta entrando el callback correctamente por lo tanto se queda en pending.

en cuanto a la notificación Online HTTP + email comercio quiere el callback entrara igualmente tanto por https o http y tambien recibirás un correo informando de la notificación del pago.

**Comment by olivermontes** [comment]
@rvaquerizo117 ya nos comenta si te hemos podido ayudar. Gracias

**Comment by evuska** [comment]
gracias mbernabeu! 
Disculpa que no te haya respondido antes!

El módulo me está funcionando bien!!! mil gracias

**Comment by rvaquerizo117** [comment]
@olivermontes, @mbernabeu muchas gracias a los dos.

Sigo con el problema, los pedidos entran en "pendiente" estén o no OK. Es un jaleo por que hay que validarlos uno por uno.

Tanto la url segura como insegura tienen el https, pero no hago referencia al código del idioma de la tienda. Os dejo una captura con la configuración actual. 

http://i.imgur.com/Faj2Bp9.png?1

Y de la configuración de vuestro módulo por si hubiera algo mal en los estados seleccionados:

http://i.imgur.com/mnIAB4d.png?1

Un saludo.

**Comment by mbernabeu** [comment]
Hola @rvaquerizo117 

veo que en la url insegura tienes puesto el https debería ser http, en algunos casos Redsys no reconoce algunos certificados https y puede ser que en tu caso falle y veo que as puesto /es pero no veo que tengas /es en la web.

Prueba a poner en url insegura http y en el callback http con eso no debería darte problemas.

**Comment by rvaquerizo117** [comment]
Gracias @mbernabeu, probaré lo que me comentas y te diré si funciona. Por cierto, en la web si es accesible https://movilesportatiles.com/es/.

Un saludo.
