### ISSUE TITLE
Problema cambio de estado pedido después de confirmación

### ISSUE THREAD

**Issue by ClickCons** [DevopensourceTeam/Devopensource_Redsys#50]
Hola!
Vuestro plugin es genial!!!!
Pero últimamente estoy teniendo unos problemillas con algunos pedidos (no con todos).
A veces después de que el banco confirme la compra y se facture el pedido se vuelve a cambiar el estado automáticamente a "Pendiente". Porque puede ser? Help!!!

![capotura](https://cloud.githubusercontent.com/assets/15377073/17360849/bd69aa48-596d-11e6-8176-14aaa0b52e9c.png)

Muchisimas gracias por anticipado.

**Comment by mbernabeu** [comment]
Hola @ClickCons que version del modulo tienes? esto lo hemos solucionado en los últimos cambios

**Comment by ClickCons** [comment]
Hola @mbernabeu ! Tengo la Devopensource_Redsys v0.2.0 (no es la última), no sabia que era un problema general y lo habíais solucionado.
Actualizo!!!!!!!!! Grazie.
