### ISSUE TITLE
Error en datos enviados. Contacte con su comercio.

### ISSUE THREAD

**Issue by lrivasg** [DevopensourceTeam/Devopensource_Redsys#51]
Hola,

Estoy probando la extensión y cuando configuro el entorno de pruebas tengo el siguiente problema:

Importe 0  Sin Asignar
Código Comercio    266635432
Terminal    1
Número pedido  
Error en datos enviados. Contacte con su comercio.

Tenéis idea de porque puede ocurrir?

Gracias.

**Comment by jruzafa** [comment]
Hola @lrivasg 

Ese error lo tira cuando no se mandan correctamente los datos a la pasarela de redsys.

Para saber mas del error inserta un log en **Devopensource/Redsys/controllers/IndexController.php** linea  43 , y tira el contenido de las variables de arriba, y comprueba los valores que sean correctos, tambien puede estar el error en la generacion de los parametros que se envian $paramsBase64 y $signatureMac.

**Comment by olivermontes** [comment]
no reply
