### ISSUE TITLE
Pedidos cancelados no devuelven productos al stock

### ISSUE THREAD

**Issue by droolo** [DevopensourceTeam/Devopensource_Redsys#57]
En los pedidos que se cancelan al recibir la notificación de denegación de Redsys, cambia el state y el status a cancelado pero los productos no se registran como "cancelados" por lo que las existencias no regresan al stock. Si no me equivoco falta incluir la línea: $order->cancel();

**Comment by mbernabeu** [comment]
Hola @droolo 

No por que para poder añadir un comentario en la cancelación con cancel no lo permite pero el modulo realiza los mismos procesos que en el cancel. asegurate de tener la ultima version del modulo y tener la configuración correcta en Magento y que ningun modulo externo este interfiriendo  ya que esto esta funcionando.

**Comment by droolo** [comment]
Hola @mbernabeu  voy a hacer pruebas con una nueva instalación para ir descartando porque tengo 3 tiendas con distintas versiones de Magento y el último módulo y en todas me ocurre lo mismo. Antes necesito que por favor me confirmes si el cron de cancelaciones afecta solo a los pedidos que no reciben respuesta de Redsys, o si también afecta a los pedidos que sí reciben la orden de denegación. Gracias.

**Comment by pachitow** [comment]
Hola @mbernabeu y @droolo 

Estoy teniendo el mismo problema en una de las tiendas de un cliente y creo que he detectado un error en el código que podría ser el causante de este incidente.
En el fichero `app/code/community/Devopensource/Redsys/Helper/Data.php`, en la función `stateErrorTpv` se realiza la siguiente llamada:
`192:         $this->setCustomState($_order,null, $status, $comment, false, false);`
en la que se pasa como segundo parámetro (`$state`) un valor `null`.
Esto provoca que al entrar en la función `setCustomState` no se cumpla nunca el primer condicional, ya que el valor del parámetro `$state` es `null`:
`449:    if($state=="canceled")`

Además he realizado una búsqueda de todas las llamadas a esta función en el código y es el único caso en el que se pasa el segundo parámetro con valor `null`.

@mbernabeu podríais decirnos si se trata de un error o este valor `null` realmente tiene algún propósito concreto?
Gracias


[Magento.Redsys.txt](https://github.com/DevopensourceTeam/Devopensource_Redsys/files/839278/Magento.Redsys.txt)

**Comment by lrivasg** [comment]
Hola @jpachecoestepa 

Tengo el mismo problema. Al final has aplicado esta solución? @mbernabeu @droolo habéis podido mirarlo?

Gracias.

**Comment by pachitow** [comment]
Hola @lrivasg 
Efectivamente hemos aplicado esta solución y, por el momento, funciona correctamente.
Queda esperar a que nos una respuesta "oficial" a este issue o al pull request #62.
Un saludo!

**Comment by mbernabeu** [comment]
Hola @jpachecoestepa @lrivasg @droolo es correcto había un bug no reponía correctamente las cantidades acabo de añadir el merge con lo cual la ultima version ya tiene esto corregido.  

Gracias @jpachecoestepa por tu contribución.
