### ISSUE TITLE
Devoluciones?

### ISSUE THREAD

**Issue by ClickCons** [DevopensourceTeam/Devopensource_Redsys#58]
Hola!!!
Que tal el tema de las devoluciones?
Soy consciente de que ahora mismo la extensión no permite generar devoluciones automáticas Magento - Redsys desde el propio administrador de Magento. Pero eso sería posible?
Por lo que he leido del webservice de Redsys hay varios tipos de transacciones (DS_MERCHANT_TRANSACTIONTYPE), es muy descabellado?
Sería útil... 

Saludos!

**Comment by jruzafa** [comment]
Hola @ClickCons,

Si, es posible hacer devoluciones desde el propio webservice de Redsys, actualmente planificando y valorando el desarrollo de esa feature, en cuanto la tengamos, avisaremos :-) 

Un saludo,
