### ISSUE TITLE
No redirecciona a plataforma redsys, sino que da el pedido por pagado

### ISSUE THREAD

**Issue by luiselkano** [DevopensourceTeam/Devopensource_Redsys#63]
Hola,

He instalado vuestra excelente forma de pago en magento  1.9.3.2 pero al ir a probarla, no redirecciona correctamente a la plataforma redsys, sino que da el pedido por pagado.

En el system.log solo aparecen estos dos warnings:
------------------------------------------------------------------------------------
2017-05-17T17:27:00+00:00 ERR (3): Warning: include(PEAR/Error.php): failed to open stream: No such file or directory  in /home/xxxx/lib/Varien/Autoload.php on line 94
2017-05-17T17:27:00+00:00 ERR (3): Warning: include(): Failed opening 'PEAR/Error.php' for inclusion (include_path='/home/xxxx/app/code/local:/home/xxxx/app/code/community:/home/xxxx/app/code/core:/home/xxxx/lib:.:/usr/share/php:/usr/share/pear')  in /home/xxxx/lib/Varien/Autoload.php on line 94
------------------------------------------------------------------------------------
La versión de php del servidor es:
PHP 5.3.10-1ubuntu3.22 with Suhosin-Patch (cli) (built: Apr 20 2016 12:31:15) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

¿Por dónde puedo comenzar a debugear?

**Comment by jruzafa** [comment]
1º Comprueba que el modulo este instalado correctamente y que lo reconoce Magento esto puedes verlo si ves la config del mismo en sistema > metodos de pago
2º Si no lo ves y esta correctamente instalado limpia los sistemas de cache que tengas conectados al Magento.
2º Que no haya otro modulo con el mismo alias de ruta https://github.com/DevopensourceTeam/Devopensource_Redsys/blob/master/app/code/community/Devopensource/Redsys/etc/config.xml#L49

**Comment by luiselkano** [comment]
Hola,

Gracias por la pronta respuesta... sobre las recomendaciones:

1.- Efectivamente, se ve en la configuración, luego está bien instalado
2.- Por si acaso, he limpiado todas las caches de magento
3.- He buscado el alias de ruta, y no hay ningún otro:

```
xxx@yyyy:/home/zzzzz/app/code# grep -nri "frontName>redsys" *
community/Devopensource/Redsys/etc/config.xml:49:                    <frontName>redsys</frontName>
```
El resultado sigue siendo el mismo. Selecciono el método de pago, aparece el resumen de la compra, y al darle a pagar vuelve a la home page y el pedido aparece como pagado.

¿Alguna otra pista?

**Comment by luiselkano** [comment]
Hola,

Misterio solucionado. La web por defecto tenía como estado de pedido inicial "Redsys - Pago realizado" y la extensión hace la siguiente comprobación:

       if($_order->getState() != "new") || $_order->getStatus() != "pending" ) { 
            $response = Mage::app()->getResponse();
             $response->setRedirect(Mage::getBaseUrl());
            $response->sendResponse();

Al no ser el status inicial "pending" no enviaba la petición a RedSys ni cambiaba el estado, sino que redirigía a la home, por eso aparecía como pagado.

Tal vez la extensión no debería usar literales como "new" o "pending", sino mirar la configuración de la tienda, pero doy el bug por cerrado
